name: CI

env:
  GODOT_VERSION: 3.3.4
  EXPORT_NAME: source_code

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - name: Dependencies
        run: |
          apt-get update
          apt-get install libssl-dev -y 
          
      - uses: actions/checkout@v2.3.2
      - run: |
          
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          mkdir -v -p build/android
          cd $EXPORT_NAME
          
          echo ${{ secrets.SECRET_RELEASE_KEYSTORE_BASE64 }} | base64 --decode > /root/release.keystore #doesnt work
          
          sed 's@keystore/release=".*"@keystore/release="'/root/release.keystore'"@g' -i export_presets.cfg
          sed 's@keystore/release_user=".*"@keystore/release_user="'${{ secrets.SECRET_RELEASE_KEYSTORE_USER }}'"@g' -i export_presets.cfg
          sed 's@keystore/release_password=".*"@keystore/release_password="'${{ secrets.SECRET_RELEASE_KEYSTORE_PASSWORD}}'"@g' -i export_presets.cfg
          
          godot -v --path /source_code/project.godot --export "Android" ../build/android/$EXPORT_NAME.apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: android
          path: build/android
