name: CI

env:
  GODOT_VERSION: 3.3.4
  EXPORT_NAME: source_code

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  container:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:3.3.4
    steps:
      - name: Dependencies
        run: |
          apt-get update -y
        
          apt-get install libssl-dev -y 
          apt install android-sdk -y
          
          apt install sdkmanager -y
          
          sdkmanager --sdk_root="/usr/lib/android-sdk" "platform-tools" "build-tools;30.0.3" "platforms;android-29" "cmdline-tools;latest" "cmake;3.10.2.4988404" "ndk;21.4.7075529"
          
          
      - name: Compile for android    
        uses: actions/checkout@v2.3.2
      - run: |
          #make template
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
          
          echo 'export/android/android_sdk_path = "/usr/lib/android-sdk"' >> ~/.config/godot/editor_settings-3.tres
          
          
          mkdir -v -p build/android
          cd $EXPORT_NAME
          
          echo ${{ secrets.SECRET_RELEASE_KEYSTORE_BASE64 }} | base64 --decode > /root/release.keystore 
          
          sed 's@keystore/release=".*"@keystore/release="'/root/release.keystore'"@g' -i export_presets.cfg
          sed 's@keystore/release_user=".*"@keystore/release_user="'${{ secrets.SECRET_RELEASE_KEYSTORE_USER }}'"@g' -i export_presets.cfg
          sed 's@keystore/release_password=".*"@keystore/release_password="'${{ secrets.SECRET_RELEASE_KEYSTORE_PASSWORD}}'"@g' -i export_presets.cfg
          
          #stops a bug. Debug keystore is invalid
          echo ${{ secrets.SECRET_RELEASE_KEYSTORE_BASE64 }} | base64 --decode > /root/debug.keystore 
          
          sed 's@keystore/debug=".*"@keystore/debug="'/root/release.keystore'"@g' -i export_presets.cfg
          sed 's@keystore/debug_user=".*"@keystore/debug_user="'${{ secrets.SECRET_RELEASE_KEYSTORE_USER }}'"@g' -i export_presets.cfg
          sed 's@keystore/debug_password=".*"@keystore/debug_password="'${{ secrets.SECRET_RELEASE_KEYSTORE_PASSWORD}}'"@g' -i export_presets.cfg
          
          godot -v --path /source_code/project.godot --export "Android" ../build/android/$EXPORT_NAME.apk
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: android
          path: build/android
