name: Android CI for 3.5.3 Branch

env:
  GODOT_VERSION: 3.6
  EXPORT_NAME: source_code

on:
  push:
    branches: [main]

jobs:
  export-binary:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:3.6
    steps:
      - name: Dependencies
        run: |
          apt-get update -y
          apt-get install libssl-dev -y 
          apt-get install android-sdk -y
          apt-get install default-jdk -y

          #Error Catcher 1
          git config --global --add safe.directory /__w/Dystopia-App/Dystopia-App

      - name: Compile for android
        uses: actions/checkout@v4
        with:
          ref: "v3.5.3"
      - run: |
          #make android export template
          mkdir -v -p ~/.local/share/godot/templates

          # move root godot binary into desktop local location
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

          #make android export template for custom build
          ls -al
          mkdir -v -p source_code/android/build

          cp -r source_code/plugins source_code/android


          # copy android build templates for custom builds
          cp ~/.local/share/godot/templates/${GODOT_VERSION}.stable/android_source.zip source_code/android/build 

          unzip -o source_code/android/build/android_source.zip -d source_code/android/build
          touch source_code/android/.build_version
          echo "${GODOT_VERSION}.stable" > source_code/android/.build_version
          cp source_code/plugins/AndroidManifest.xml  source_code/android/build
          # Create Android sdk path in editor settings
          sed 's|export/android/android_sdk_path = ".*"|export/android/android_sdk_path = "'/usr/lib/android-sdk'"|g' -i /root/.config/godot/editor_settings-3.tres
          mkdir -v -p ~/.config/godot
          cp -v /root/.config/godot/editor_settings-3.tres ~/.config/godot/
          mkdir -v -p build/android

          # debug file paths
          ls -al

          cd $EXPORT_NAME

          #android version



          #sets release keystore
          echo ${{ secrets.SECRET_RELEASE_KEYSTORE_BASE64 }} | base64 --decode > /root/release.keystore 

          sed 's@keystore/release=".*"@keystore/release="'/root/release.keystore'"@g' -i export_presets.cfg
          sed 's@keystore/release_user=".*"@keystore/release_user="'${{ secrets.SECRET_RELEASE_KEYSTORE_USER }}'"@g' -i export_presets.cfg
          sed 's@keystore/release_password=".*"@keystore/release_password="'${{ secrets.SECRET_RELEASE_KEYSTORE_PASSWORD}}'"@g' -i export_presets.cfg

          #stops a bug. Debug keystore is invalid
          echo ${{ secrets.SECRET_RELEASE_KEYSTORE_BASE64 }} | base64 --decode > /root/debug.keystore 

          sed 's@keystore/debug=".*"@keystore/debug="'/root/release.keystore'"@g' -i export_presets.cfg
          sed 's@keystore/debug_user=".*"@keystore/debug_user="'${{ secrets.SECRET_RELEASE_KEYSTORE_USER }}'"@g' -i export_presets.cfg
          sed 's@keystore/debug_password=".*"@keystore/debug_password="'${{ secrets.SECRET_RELEASE_KEYSTORE_PASSWORD}}'"@g' -i export_presets.cfg

          #changes the verion name and number
          sed 's@version/name=".*"@version/name="'${{ github.run_number }}'"@g' -i export_presets.cfg

          #if the version number is set to "", this line of code works #doens't work disabling
          #sed 's@version/code=".*"@version/code=${{ github.run_number }}@g' -i export_presets.cfg


          #export the binary as aab
          godot --headless --verbose /source_code/project.godot --export "Android" ../build/android/$EXPORT_NAME.apk

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/android/source_code.apk
          compression-level: 9

  Itch_io:
    runs-on: ubuntu-22.04
    needs: export-binary
    steps:
      - name: Download content
        uses: actions/download-artifact@v4
        with:
          name: android
          path: ./android

      - name: Butler Publish
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: androids
          ITCH_GAME: dystopia-app
          ITCH_USER: inhumanity-arts
          PACKAGE: ./android/source_code.apk
          BUTLER_EXTRA_ARGS: --userversion 1.0.0
